name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Compile
        uses: addnab/docker-run-action@v3
        with:
          image: rust:1.67.0-slim-bullseye
          options: -v ${{ github.workspace }}:/app
          run: |
            apt-get update && apt-get install openssl-dev
            cd /app
            ls -al
            cargo build
            ls -al
