name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run Container to compile the application
        uses: docker://rust:1.67.0-slim-bullseye
        with:
          args: >-
            "ls -al /github/workspace"
      - name: List files
        run: ls -al /app
